package me.theredbaron24.paintball.kits;

public enum KitType {
	NONE, DASHER, GRENADIER, SPRAYER, SNIPER, BOMBER, DEMO, ROCKETMAN, BLASTER,
	GUNNER, RELOADER, HEALER, HEAVY, BLOCKER, BLINDER, CHARGER, JUGGERNAUT, BOUNCER;
}
